### ISSUE TITLE
Data is not displayed

### ISSUE THREAD

**Issue by vladns** [DASPRiD/vnstat-php#7]
The main page only displays two lines:
Network Traffic
Hourly
No more data available. Apache2 log:
`[Mon Jul 27 12:57:16.261503 2020] [php7:notice] [pid 325079] [client 192.168.2.1:45518] PHP Notice:  Undefined offset: 13 in /var/www/vnstat-php/index.php on line 169, referer: http://home-router/
[Mon Jul 27 12:57:16.261567 2020] [php7:error] [pid 325079] [client 192.168.2.1:45518] PHP Fatal error:  Uncaught Error: Call to a member function getBytesReceived() on null in /var/www/vnstat-php/index.php:170\nStack trace:\n#0 {main}\n  thrown in /var/www/vnstat-php/index.php on line 170, referer: http://home-router/`
![2020-07-27_125108](https://user-images.githubusercontent.com/22105830/88529844-39ba1180-d009-11ea-9089-42d88b839d34.png)

**Comment by DASPRiD** [comment]
Sounds like you either don't have `vnstat` installed, the user has no access to it or it doesn't dump the full database. Is `vnstat --dumpdb` outputting something for you under the web user?

**Comment by vladns** [comment]
I already understood what was the matter.
`root@router:~# vnstat --dumpdb
Unknown parameter "--dumpdb". Use --help for help.`

**Comment by DASPRiD** [comment]
Huh, that's interesting. Which version of vnStat are you using?

**Comment by vladns** [comment]
The developers removed some of the options, including this one. For example, there is a justification here: https://github.com/vergoh/vnstat/issues/141
Ubuntu 20.04.1 LTS, vnStat 2.6

**Comment by DASPRiD** [comment]
Fixed with latest commit, thanks for the report!

**Comment by vladns** [comment]
I still see the error http 500. Apache2 log:
`[Tue Jul 28 21:48:43.544729 2020] [php7:notice] [pid 593873] [client 192.168.2.1:50348] PHP Notice:  Undefined index: id in /var/www/vnstat-php/Vnstat/Database.php on line 80, referer: http://home-router/
[Tue Jul 28 21:48:43.544792 2020] [php7:notice] [pid 593873] [client 192.168.2.1:50348] PHP Notice:  Undefined index: nick in /var/www/vnstat-php/Vnstat/Database.php on line 81, referer: http://home-router/
[Tue Jul 28 21:48:43.556909 2020] [php7:notice] [pid 593873] [client 192.168.2.1:50348] PHP Notice:  Undefined index: minutes in /var/www/vnstat-php/Vnstat/Database.php on line 224, referer: http://home-router/
[Tue Jul 28 21:48:43.556948 2020] [php7:notice] [pid 593873] [client 192.168.2.1:50348] PHP Notice:  Undefined index: days in /var/www/vnstat-php/Vnstat/Database.php on line 88, referer: http://home-router/
[Tue Jul 28 21:48:43.556962 2020] [php7:warn] [pid 593873] [client 192.168.2.1:50348] PHP Warning:  Invalid argument supplied for foreach() in /var/www/vnstat-php/Vnstat/Database.php on line 88, referer: http://home-router/
[Tue Jul 28 21:48:43.556973 2020] [php7:notice] [pid 593873] [client 192.168.2.1:50348] PHP Notice:  Undefined index: months in /var/www/vnstat-php/Vnstat/Database.php on line 97, referer: http://home-router/
[Tue Jul 28 21:48:43.556983 2020] [php7:warn] [pid 593873] [client 192.168.2.1:50348] PHP Warning:  Invalid argument supplied for foreach() in /var/www/vnstat-php/Vnstat/Database.php on line 97, referer: http://home-router/
[Tue Jul 28 21:48:43.556993 2020] [php7:notice] [pid 593873] [client 192.168.2.1:50348] PHP Notice:  Undefined index: tops in /var/www/vnstat-php/Vnstat/Database.php on line 106, referer: http://home-router/
[Tue Jul 28 21:48:43.557018 2020] [php7:warn] [pid 593873] [client 192.168.2.1:50348] PHP Warning:  Invalid argument supplied for foreach() in /var/www/vnstat-php/Vnstat/Database.php on line 106, referer://http://home-router/
[Tue Jul 28 21:48:43.557029 2020] [php7:notice] [pid 593873] [client 192.168.2.1:50348] PHP Notice:  Undefined index: hours in /var/www/vnstat-php/Vnstat/Database.php on line 115, referer: http://home-router/
[Tue Jul 28 21:48:43.557038 2020] [php7:warn] [pid 593873] [client 192.168.2.1:50348] PHP Warning:  Invalid argument supplied for foreach() in /var/www/vnstat-php/Vnstat/Database.php on line 115, referer://http://home-router/
[Tue Jul 28 21:48:43.576628 2020] [php7:notice] [pid 593873] [client 192.168.2.1:50348] PHP Notice:  Undefined offset: 22 in /var/www/vnstat-php/index.php on line 169, referer: http://home-router/
[Tue Jul 28 21:48:43.576713 2020] [php7:error] [pid 593873] [client 192.168.2.1:50348] PHP Fatal error:  Uncaught Error: Call to a member function getBytesReceived() on null in /var/www/vnstat-php/index.php:170\nStack trace:\n#0 {main}\n  thrown in /var/www/vnstat-php/index.php on line 170, referer: http://home-router/
[Tue Jul 28 21:48:48.568050 2020] [php7:notice] [pid 593730] [client 192.168.2.1:50366] PHP Notice:  Undefined index: id in /var/www/vnstat-php/Vnstat/Database.php on line 80, referer: http://home-router/
[Tue Jul 28 21:48:48.568118 2020] [php7:notice] [pid 593730] [client 192.168.2.1:50366] PHP Notice:  Undefined index: nick in /var/www/vnstat-php/Vnstat/Database.php on line 81, referer: http://home-router/
[Tue Jul 28 21:48:48.574355 2020] [php7:notice] [pid 593730] [client 192.168.2.1:50366] PHP Notice:  Undefined index: minutes in /var/www/vnstat-php/Vnstat/Database.php on line 224, referer: http://home-router/
[Tue Jul 28 21:48:48.574392 2020] [php7:notice] [pid 593730] [client 192.168.2.1:50366] PHP Notice:  Undefined index: days in /var/www/vnstat-php/Vnstat/Database.php on line 88, referer: http://home-router/
[Tue Jul 28 21:48:48.574405 2020] [php7:warn] [pid 593730] [client 192.168.2.1:50366] PHP Warning:  Invalid argument supplied for foreach() in /var/www/vnstat-php/Vnstat/Database.php on line 88, referer: http://home-router/
[Tue Jul 28 21:48:48.574417 2020] [php7:notice] [pid 593730] [client 192.168.2.1:50366] PHP Notice:  Undefined index: months in /var/www/vnstat-php/Vnstat/Database.php on line 97, referer: http://home-router/
`

**Comment by DASPRiD** [comment]
Hm, I wonder if the JSON output changed between versions. Can you gist the output of your `vnstat --json`?

**Comment by vladns** [comment]
[vnstat --json.txt](https://github.com/DASPRiD/vnstat-php/files/4997370/vnstat.--json.txt)

**Comment by vladns** [comment]
Is there any news?

**Comment by DASPRiD** [comment]
I actually just pushed a fix for version 2 JSON schema support. Please test.

**Comment by vladns** [comment]
Without changes. Maybe I'm doing something wrong?

```
[Mon Aug 03 21:43:49.841604 2020] [php7:notice] [pid 544770] [client 192.168.2.1:52886] PHP Notice:  Undefined index: days in /var/www/vnstat-php/Vnstat/Database.php on line 107, referer: http://home-router/
[Mon Aug 03 21:43:49.841646 2020] [php7:warn] [pid 544770] [client 192.168.2.1:52886] PHP Warning:  Invalid argument supplied for foreach() in /var/www/vnstat-php/Vnstat/Database.php on line 107, referer: http://home-router/
[Mon Aug 03 21:43:49.841656 2020] [php7:notice] [pid 544770] [client 192.168.2.1:52886] PHP Notice:  Undefined index: months in /var/www/vnstat-php/Vnstat/Database.php on line 116, referer: http://home-router/
[Mon Aug 03 21:43:49.841663 2020] [php7:warn] [pid 544770] [client 192.168.2.1:52886] PHP Warning:  Invalid argument supplied for foreach() in /var/www/vnstat-php/Vnstat/Database.php on line 116, referer: http://home-router/
[Mon Aug 03 21:43:49.841671 2020] [php7:notice] [pid 544770] [client 192.168.2.1:52886] PHP Notice:  Undefined index: tops in /var/www/vnstat-php/Vnstat/Database.php on line 125, referer: http://home-router/
[Mon Aug 03 21:43:49.841678 2020] [php7:warn] [pid 544770] [client 192.168.2.1:52886] PHP Warning:  Invalid argument supplied for foreach() in /var/www/vnstat-php/Vnstat/Database.php on line 125, referer: http://home-router/
[Mon Aug 03 21:43:49.841685 2020] [php7:notice] [pid 544770] [client 192.168.2.1:52886] PHP Notice:  Undefined index: hours in /var/www/vnstat-php/Vnstat/Database.php on line 134, referer: http://home-router/
[Mon Aug 03 21:43:49.841692 2020] [php7:warn] [pid 544770] [client 192.168.2.1:52886] PHP Warning:  Invalid argument supplied for foreach() in /var/www/vnstat-php/Vnstat/Database.php on line 134, referer: http://home-router/
[Mon Aug 03 21:43:49.843435 2020] [php7:notice] [pid 544770] [client 192.168.2.1:52886] PHP Notice:  Undefined offset: 22 in /var/www/vnstat-php/index.php on line 169, referer: http://home-router/
[Mon Aug 03 21:43:49.843478 2020] [php7:error] [pid 544770] [client 192.168.2.1:52886] PHP Fatal error:  Uncaught Error: Call to a member function getBytesReceived() on null in /var/www/vnstat-php/index.php:170\nStack trace:\n#0 {main}\n  thrown in /var/www/vnstat-php/index.php on line 170, referer: http://home-router/
```
I get a white screen, with a choice of interfaces.

**Comment by DASPRiD** [comment]
I pushed some additional fixes.

**Comment by vladns** [comment]
```
[Tue Aug 04 11:02:57.092570 2020] [php7:notice] [pid 1063891] [client 192.168.2.1:54968] PHP Notice:  Undefined offset: 23 in /var/www/vnstat-php/index.php on line 169, referer: http://home-router/
[Tue Aug 04 11:02:57.092637 2020] [php7:error] [pid 1063891] [client 192.168.2.1:54968] PHP Fatal error:  Uncaught Error: Call to a member function getBytesReceived() on null in /var/www/vnstat-php/index.php:170\nStack trace:\n#0 {main}\n  thrown in /var/www/vnstat-php/index.php on line 170, referer: http://home-router/
[Tue Aug 04 11:03:00.391112 2020] [php7:notice] [pid 1063891] [client 192.168.2.1:55002] PHP Notice:  Undefined offset: 23 in /var/www/vnstat-php/index.php on line 169, referer: http://home-router/
[Tue Aug 04 11:03:00.391168 2020] [php7:error] [pid 1063891] [client 192.168.2.1:55002] PHP Fatal error:  Uncaught Error: Call to a member function getBytesReceived() on null in /var/www/vnstat-php/index.php:170\nStack trace:\n#0 {main}\n  thrown in /var/www/vnstat-php/index.php on line 170, referer: http://home-router/
[Tue Aug 04 11:03:02.809195 2020] [php7:notice] [pid 1063891] [client 192.168.2.1:55044] PHP Notice:  Undefined offset: 23 in /var/www/vnstat-php/index.php on line 169, referer: http://home-router/
[Tue Aug 04 11:03:02.809261 2020] [php7:error] [pid 1063891] [client 192.168.2.1:55044] PHP Fatal error:  Uncaught Error: Call to a member function getBytesReceived() on null in /var/www/vnstat-php/index.php:170\nStack trace:\n#0 {main}\n  thrown in /var/www/vnstat-php/index.php on line 170, referer: http://home-router/
[Tue Aug 04 11:03:46.702631 2020] [php7:notice] [pid 1063879] [client 192.168.2.1:55374] PHP Notice:  Undefined offset: 23 in /var/www/vnstat-php/index.php on line 169, referer: http://home-router/
[Tue Aug 04 11:03:46.702790 2020] [php7:error] [pid 1063879] [client 192.168.2.1:55374] PHP Fatal error:  Uncaught Error: Call to a member function getBytesReceived() on null in /var/www/vnstat-php/index.php:170\nStack trace:\n#0 {main}\n  thrown in /var/www/vnstat-php/index.php on line 170, referer: http://home-router/
[Tue Aug 04 11:03:49.672503 2020] [php7:notice] [pid 1063891] [client 192.168.2.1:55420] PHP Notice:  Undefined offset: 23 in /var/www/vnstat-php/index.php on line 169, referer: http://home-router/
[Tue Aug 04 11:03:49.672558 2020] [php7:error] [pid 1063891] [client 192.168.2.1:55420] PHP Fatal error:  Uncaught Error: Call to a member function getBytesReceived() on null in /var/www/vnstat-php/index.php:170\nStack trace:\n#0 {main}\n  thrown in /var/www/vnstat-php/index.php on line 170, referer: http://home-router/

```

**Comment by DASPRiD** [comment]
Ah, silly off-by-one error, fixed :)

**Comment by vladns** [comment]
Works, but:
![2020-08-04_174302](https://user-images.githubusercontent.com/22105830/89307849-3c0c1380-d67a-11ea-9d4c-07692b150acf.png)

**Comment by DASPRiD** [comment]
Right, your database dump does not contain any hour values for the current timeframe.

**Comment by vladns** [comment]
I did not find how the user can influence the formation of the database. I just found this: vnstat --json h --limit 1 (part of the output)
```
{"name":"ppp0","alias":"","created":{"date":{"year":2014,"month":11,"day":23}},"updated":{"date":{"year":2020,"month":8,"day":4},"time":{"hour":19,"minute":15}},"traffic":{"total":{"rx":104548201243707,"tx":1078381288336416},"hour":[{"id":918,"date":{"year":2020,"month":8,"day":4},"time":{"hour":19,"minute":0},"rx":673429447,"tx":10592500154}]}}
```
Not sure exactly, but it seems that "time": {"hour": 19, "minute": 0} counts hourly traffic?

**Comment by DASPRiD** [comment]
Right. Is ppp0 the interface you are looking at though in vnstat-php?

**Comment by vladns** [comment]
Yes.

**Comment by vladns** [comment]
Apologies for asking again, but is there any news?
